### ISSUE TITLE
TLS config for Jaeger gRPC receiver

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-opentelemetry-collector#22]
Was discussed in https://github.com/open-telemetry/opentelemetry-collector/pull/197#issuecomment-516616139.

**Comment by jpkrohling** [comment]
With the current OpenTelemetry Collector master, the following configuration is able to open a receiver with TLS:

```yaml
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: "localhost:14250"
        tls_credentials:
          cert_file: /tmp/certificate.pem
          key_file: /tmp/key.pem

processors:
  queued_retry:
    retry_on_failure: true

exporters:
  jaeger_grpc:
    endpoint: "localhost:15250"

service:
  pipelines:
    traces:
      receivers: [jaeger]
      processors: [queued_retry]
      exporters: [jaeger_grpc]
```

With this config file at `/tmp/otelcol.yaml`, it can be started as:

```
$ go run ./cmd/otelcol --config /tmp/otelcol.yaml 
```

The certs used are the ones from the [test data directory](https://github.com/open-telemetry/opentelemetry-collector/tree/master/receiver/jaegerreceiver/testdata) in the same repository.

I confirmed that it works by starting an agent like this:
```
$ go run ./cmd/agent --reporter.grpc.tls.enabled=true --reporter.grpc.tls.ca=/tmp/certificate.pem --reporter.grpc.host-port=localhost:14250 --reporter.grpc.tls.server-name=opentelemetry.io
```
