### ISSUE TITLE
Are thrift_http and grpc exporters required?

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-opentelemetry-collector#26]
Currently the Jaeger exporter in OTC supports both thrift/http and gRPC. This has been implemented as separate exporters, resulting in this type of config:
```
  jaeger_grpc:
    endpoint: "http://localhost:14250"

  jaeger_thrift_http:
    headers: {"X-test-header": "test-header"}
    timeout: 5
    url: "http://localhost:14268/api/traces"

  zipkin:
    url: "http://localhost:9411/api/v2/spans"
```
(zipkin included for comparison).

I am not sure there is anything to be gained from having both options - as the only receiving component will be another OTC or the Jaeger Collector - so gRPC should be adequate.

If however both transports are required, then it should atleast be combined into a single exporter with options to determine the transport.

Thoughts?
