### ISSUE TITLE
Configuration file and flags

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-opentelemetry-collector#7]
An example configuration:
```
receivers:
  examplereceiver:

processors:
  exampleprocessor:

exporters:
  jaeger_elasticsearch:
    server_urls: "http://localhost:9200"
  jaeger_elasticsearch/backup:
    server_urls: "http://localhost:9200"
    index_prefix: "backup"
  jaeger_cassandra:
    servers: "cassandra:9042"

service:
  pipelines:
    traces:
      receivers: [examplereceiver]
      processors: [exampleprocessor]
      exporters: [jaeger_elasticsearch, jaeger_elasticsearch/backup, jaeger_cassandra]
```

As it can be seen from the config it is possible to use multiple storage exporters (and of the same type) in a single pipeline.

The fact that multiple exporters of the same type can be used it makes it hard to expose the configuration as flags or env variables.
