### ISSUE TITLE
Serve sampling strategies 

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-opentelemetry-collector#9]
Serve sampling strategies file

At the moment collector just proxies calls. Done in https://github.com/open-telemetry/opentelemetry-collector/pull/448

**Comment by pavolloffay** [comment]
Might be done in https://github.com/open-telemetry/opentelemetry-collector/issues/500

**Comment by objectiser** [comment]
This has been done as part of https://github.com/open-telemetry/opentelemetry-collector/pull/547 - however it only works over gRPC.

Now that [`/api/sampling` is available in Jaeger collector](https://github.com/jaegertracing/jaeger/pull/1990), since 1.17.0, that should be supported aswell.

cc @joe-elliott

**Comment by joe-elliott** [comment]
The opentelemetry collector supports both http proxy (jaeger agent) and GRPC (jaeger collector) for serving sampling strategies.  It's a little strange, but technically an operator could configure their opentelemetry collector to proxy to itself.  The config would look something like:
```
receivers:
  jaeger:
    protocols:
      grpc:
    remote_sampling:
      fetch_endpoint: "localhost:14250"
      strategy_file: "/etc/strategies.json"
```

This work was done before we knew about the jaeger-opentelemetry-collector.  Now that it exists I don't know if we should reevaluate some of the functionality in the collector.
